# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: 2ndPipeline

trigger: none

resources:
  pipelines:
  - pipeline: triggerd-by-dummy-main-pipeline
    source: liviutomoiaga.master
    project: LiviusPlayground
    trigger: true

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '$(System.TeamProject)'
    pipeline: 'liviutomoiaga.master' # The name of the pipeline you want to download from
    buildVersionToDownload: 'latest' # Or 'latestFromBranch'
    artifactName: 'drop' # The name of the artifact you want to download
    downloadPath: '$(System.DefaultWorkingDirectory)'
  displayName: 'Download Artifacts'

- script: |
    # Example: A simple deployment step that uses the downloaded binary
    ls -l $(System.DefaultWorkingDirectory)
    cat $(System.DefaultWorkingDirectory)/drop/myapp.bin
  displayName: 'Use Downloaded Artifacts'
