# Starter pipeline

parameters:
  - name: OWNER
    displayName: 'GitHub Repository Owner'
    type: string
    default: ''
  - name: REPO
    displayName: 'GitHub Repository Name'
    type: string
    default: ''
  - name: COMMIT_SHA
    displayName: 'Commit SHA to update status for'
    type: string
    default: ''
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: 2ndPipeline

trigger: none

resources:
  pipelines:
  - pipeline: triggerd-by-dummy-main-pipeline
    source: liviutomoiaga.master
    project: LiviusPlayground
    trigger: true

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '$(System.TeamProject)'
    pipeline: 'liviutomoiaga.master' # The name of the pipeline you want to download from
    buildVersionToDownload: 'latest' # Or 'latestFromBranch'
    artifactName: 'drop' # The name of the artifact you want to download
    downloadPath: '$(System.DefaultWorkingDirectory)'
  displayName: 'Download Artifacts'

- script: |
    # Example: A simple deployment step that uses the downloaded binary
    ls -l $(System.DefaultWorkingDirectory)
    cat $(System.DefaultWorkingDirectory)/drop/myapp.bin
  displayName: 'Use Downloaded Artifacts'

- script: |
    echo "Sending POST request to GitHub checks endpoint..."
    if [ -n "${{ parameters.OWNER }}" ] && [ -n "${{ parameters.REPO }}" ] && [ -n "${{ parameters.COMMIT_SHA }}" ]; then
      if [ "$AGENT_JOBSTATUS" = "Succeeded" ]; then
        STATE="success"
        DESC="All checks have passed"
      else
        STATE="failure"
        DESC="Some checks have failed"
      fi
      curl -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $(GIT_TOKEN)" \
        -H "Content-Type: application/json" \
        -d "{\"state\": \"$STATE\", \"description\": \"$DESC\", \"context\": \"ci/azure-pipelines\"}" \
        "https://api.github.com/repos/${{ parameters.OWNER }}/${{ parameters.REPO }}/statuses/${{ parameters.COMMIT_SHA }}"
    else
      echo "OWNER, REPO, or COMMIT_SHA not set. Skipping GitHub status notification."
    fi
  displayName: 'Notify GitHub: All checks have passed or failed'
  # condition: and(always(), eq(variables['Build.Reason'], 'Pipeline'))
  env:
    GIT_TOKEN: $(GIT_TOKEN)
    